sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t wk/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true wk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-west-2-428880878096"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY